# Generated by Django 5.0.2 on 2024-02-13 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="photo",
        ),
    ]
