# Generated by Django 5.0.1 on 2024-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.FileField(
                default=None, upload_to="blog/media/user_post_uploads/"
            ),
        ),
    ]
